# DETERMINAN

## Definisi Determinan

Determinan merupakan ukuran skalar dari matriks yang didapat dari nilai yang dihitung dari unsur-unsur matriks persegi, yaitu matriks yang memiliki jumlah baris dan kolom (ordo) yang sama.

## SIFAT-SIFAT DETERMINAN

1. Determinan dari suatu matriks identitas asalah 1.

In [1]:
import numpy as np

A = np.array([[1,0,0], [0,1,0], [0,0,1]])
B = np.array([[1,0], [0,1]])
print("Matriks A : \n", A)
print("Matriks B : \n", B)


Matriks A : 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Matriks B : 
 [[1 0]
 [0 1]]


In [2]:
C = np.linalg.det(A)
print(C)

1.0


## Determinan dari matriks AB sama dengan determinan matriks A dikali determinan Matriks B

In [12]:
import numpy as np

A = np.array([[2, 1], [3, 2]])
B = np.linalg.inv(A)
a = np.linalg.det(A)
b = np.linalg.det(B)

print("determinan matriks A : ", round(a))
print("determinan matriks B : ",round(b))
C = a*b
print("det.A x det.B :",round(C))
print(A@B)

determinan matriks A :  1
determinan matriks B :  1
det.A x det.B : 1
[[1. 0.]
 [0. 1.]]


## Apabila baris matriks merupakan kelipatan dari baris lainnya, maka determinannya bernilai 0.

In [19]:
A = np.array([[1, 2, 3],[2, 4, 6],[3,2,1]])
a = np.linalg.det(A)

print(A, "\n")
print(round(a))

[[1 2 3]
 [2 4 6]
 [3 2 1]] 

0


## Apabila kolom dari suatu matriks merupakan kelipatan dali kolom lainnya, maka determinanannya bernilai 0

In [2]:
import numpy as np

A = np.array([[1, 2, 3],[2, 4, 6],[3,6,9]])
a = np.linalg.det(A)

print(A, "\n")
print(round(a))

[[1 2 3]
 [2 4 6]
 [3 6 9]] 

0


# EKSPANSI KOFAKTOR

Ekspansi kofaktor merupakan metode untuk menghitung determinan dari suatu matriks dengan menyatakan determinannya dalam bentuk determinan dari matriks-matriks yang lebih kecil.




Diberikan matriks $A$:

$A = \begin{bmatrix}
2 & 1 & 0 & 3 \\
0 & -1 & 2 & 1 \\
-2 & 4 & 1 & 0 \\
1 & 3 & -2 & 1
\end{bmatrix} = a_{11}c_{11} + a_{12}c_{12} + a_{13}c_{13} + a_{14}c_{14}$

Langkah-langkah untuk menghitung determinan menggunakan ekspansi kofaktor:

a. Kofaktor dari (a_{11} = 2):

$(-1)^{1+1}det = \begin{bmatrix}
-1 & 2 & 1 \\
4 & 1 & 0 \\
3 & -2 & 1\\
\end{bmatrix}$

$c_{11} = \begin{bmatrix}
-1 & 2 & 1 \\
4 & 1 & 0 \\
3 & -2 & 1\\
\end{bmatrix}$

= (-1) ((1) (1) - (2) (-2)) - 2 ((4) (1) - (3) (0)) + 1 ((4) (-2) - (3) (1))

= (-1)((1 + 4) - (0)) - 2 ((4) - (0)) + 1 ((-8) - (3)) 

= (-1)(5) - 2(4) + 1(-11) 

= -5 - 8 - 11 

= -24

$C_{11} = (-1)^{1+1}.(-24) = 24$

b. Kofaktor dari (a_{12} = 1):

$(-1)^{1+1}det = \begin{bmatrix}
0 & 2 & 1 \\
-2 & 1 & 0 \\
1 & -2 & 1
\end{bmatrix}$

= (0)((1)(1) - (2)(-2)) - 2((0)(1) - (1)(1)) + 1((-2)(1) - (1)(1)) 

= (0 + 4) - 2(0 - 1) + 1((-2) - 1) 

= 4 - 2( - 1) + 1(-3) 

= 4 + 2 - 3 

= 3

$C_{12} = (-1)^{1+2} . 3 = (-1)(3) = -3$

c. Kofaktor dari (a_{13} = 0):

$(-1)^{1+3}det= \begin{bmatrix}
0 & -1 & 2 \\
-2 & 4 & 1 \\
1 & 3 & -2
\end{bmatrix}$

= (0)((4)(-2) - (1)(3)) - (-1)((-2)(-2) - (1)(1)) + 2((-2)(3) - (4)(1)) \\

= (0)((-8) - 3) - (-1)((4) - (1)) + 2((-6) - (4)) \\

= (0)(-11) - (-1)(3) + 2(-10) \\

= 0 + 3 - 20 \\

= -17

$C_{13} = (-1)^{1+3} . (-17) = (-1)(-17) = 17$

d. Kofaktor dari ( a_{14} = 3 ):

$(-1)^{1+4}det = \begin{bmatrix}
0 & -1 & 2 \\
-2 & 4 & 1 \\
1 & 3 & -2
\end{bmatrix}$

= 0-(-1).(-2.(-2)-1.1) + 2.(-2.3-4.1)

=0-(4-1) + 2.(-6-4)

=0-3-20

=-23

$C_{14} = (-1)^{1+4}. (-23) = -23$


Determinan dari matriks $A$:

$\det(A) = a_{11} . C_{11} + a_{12} . C_{12} + a_{13} . C_{13} + a_{14} . C_{14} \\
= (2)(24) + (1)(-3) + (0)(17) + (3)(-23) \\
= 48 - 3 + 0 -69 \\
= -24$


Jadi, determinan dari matriks \(A\) adalah -24.

