# EIGEN VALUE & EIGEN VECTOR

# KONSEP EIGEN VALUE & EIGEN VECTOR

  Jika terdapat vektor tidak nol x dan skalar skalar λ sehingga

 **Ax = λx**

  maka λ disebut eigenvalue dari A, dan x disebut eigenvector, yang nilainya bersesuai dengan eigenvalue λ.

  Vektor nol tidak bisa menjadi vektor eigen meskipun A0 = λ0, namun λ = 0 bisa menjadi nilai eigen.

  Untuk membuat persamaan linier ini memiliki solusi bukan nol (yaitu membuat dimensi ruang nol bukan nol), matriks (A − λI ) tidak boleh berupa matriks rank penuh (full rank) Dinyatakan dalam bentuk determinan:

  **det (A − λI ) = 0**





# CONTOH MENGHITUNG EIGENVALUE & EIGENVECTOR PADA MATRIKS BERORDO 2X2 DAN 3X3

In [9]:
#MATRIKS 2X2

import numpy as np
from numpy.linalg import eig

A = np.array([[1, 4],[2, 3]])

w,v = eig(A)

print("Matriks A =\n", A)
print('E-value =\n', w)
print('E-value =\n', v.round())

Matriks A =
 [[1 4]
 [2 3]]
E-value =
 [-1.  5.]
E-value =
 [[-1. -1.]
 [ 0. -1.]]


In [16]:
#MATRIKS 3X3

import numpy as np
from numpy.linalg import eig

A = np.array([[1, 4, 5], [2, 3, 5], [3, 6, 1]])

w,v = eig(A)

print("Matriks A =\n", A)
print()
print('E-value =\n', w.round())
print()
print('E-value =\n', v.round())

Matriks A =
 [[1 4 5]
 [2 3 5]
 [3 6 1]]

E-value =
 [10. -1. -4.]

E-value =
 [[-1. -1. -0.]
 [-1.  0. -0.]
 [-1.  0.  1.]]


# PCA melalui Decomposisi Nilai Eigen (EVD)

Secara konvensional, PCA didasarkan pada EVD pada matriks kovarian sampel C. Mengasumsikan bahwa X sudah dicenter:

C berbentuk p × p. Ia simetris dan karenanya selalu dapat didiagonalkan. Kita dapat menerapkan decomposisi nilai eigen:

**C = Q Λ QT**


Di mana:

Q adalah matriks ortogonal dan kolom-kolomnya adalah vektor-vektor eigen dari C (Q = [q₁, q₂, ..., qₚ]). Λ adalah matriks diagonal dengan nilai eigen dalam urutan menurun pada diagonalnya (λ₁ ≥ λ₂ ≥ ... ≥ λₚ ≥ 0).

# IMPLEMENTASI EIGENVALUE & EIGENVECTOR DENGAN PROSEDUR PCA MELALUI EVD MENGGUNAKAN PYTHON

In [21]:
import numpy as np

def pcaSVD(X):
  #pemusatan X yang nantinya akan mendapatkan matriks kovarian C
    n, p = X.shape
    X_centered = X - X.mean(axis=0)

    u, sigma, vt = np.linalg.svd(X_centered, full_matrices=False)

    # Mengembalikan komponen utama dan eigenvalue untuk menghitung proporsi varians sampel
    return (X_centered @ vt.T), (sigma**2) / (n-1)

x = np.array([[1, 3], [2, 1]])

komponen_utama, eigenvalue = pcaSVD(x)
print("Komponen utama=\n", komponen_utama.round())
print("Eigenvalue=\n", eigenvalue.round())


Komponen utama=
 [[-1.  0.]
 [ 1. -0.]]
Eigenvalue=
 [2. 0.]


# PCA melalui Singular Value Decomposition (SVD)

Untuk matriks X, selalu ada matriks-matriks U, Σ, V sehingga:

**X = U Σ VT**


Baik U maupun V adalah matriks ortogonal dan Σ adalah matriks diagonal. Elemen-elemen diagonal dari Σ disebut nilai singular (σ₁ ≥ σ₂ ≥ ... ≥ σₚ ≥ 0).


Kolom-kolom dari V adalah arah utama, dan nilai eigen ke-i λᵢ = σᵢ²/(n-1). Komponen utama dapat diperoleh dengan XV = UΣ.