# MATRIKS

# 1.  PENGERTIAN MATRIKS

  Sekumpulan bilangan yang disusun dalam baris dan kolom sehingga membentuk persegi atau persegi panjang dengan diapit oleh tanda kurung siku "[ ]" atau kurung biasa "( )". Bilangan-bilangan yang menyusun matriks inilah yang disebut sebagai elemen-elemen penyusun matriks. Matriks sering digunakan untuk mempresentasikan data terstruktur, seperti sistem persamaan linear, tranformasi geometris, dan data dalam pemrosesan citra.

# 2. PENAMAAN SUATU MATRIKS

  Pada umumnya, suatu matriks diberi nama atau diinisialisasikan dengan menggunakan huruf kapital, seperti A, B, C, G, H, J dan sebagainya. Sedangkan anggota matriks atau elemen-elemen matriks dinyatakan dengan huruf kecil, seperti a, b, c, g, h, j, dan sebagainya. Namun, anggota atau elemen dari suatu matriks juga dapat dinyatakan dengan huruf kecil yang berindeks ganda (aij), dengan ketentuan indeks pertama menyatakan di baris mana anggota itu terletak atau berada dan indeks kedua menyatakan di kolom mana anggota itu terletak. Contohnya, a21 memiliki arti anggota a terletak pada baris kedua dan kolom kesatu.

  Contoh matriks sesuai dengan ketentuan penamaan matriks:

  $$
  A =
  \begin{bmatrix}
  a & b & c \\
  d & e & f \\
  g & h & i \\
  \end{bmatrix}
  $$








# 3. ISTILAH-ISTILAH PADA MATRIKS

  a. Elemen matriks adalah anggota yang biasanya berupa bilangan yang menyusun suatu matriks. Elemen ini berada dalam koordinat baris dan kolom.

  b. Baris adalah koordinat matriks dimana elemen matriks disusun secara horizontal.

  c. Kolom adalah koordinat matriks dimana elemen matriks disusun secara vertikal.

  d. Ordo adalah ukuran yang digunakan yang biasanya disimbolkan dengan mxn. "m" menujukkan jumlah baris dan "n" menunjukkan jumlah kolom. Contohnya:

  $$
  A =
  \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9 \\
  \end{bmatrix}
  $$

  Matriks A di atas berordo atau berukuran 3x3 yang artinya matriks A di atas memiliki 3 baris dan 3 kolom.

  e. Tranpose adalah metode dalam matriks yang dapat menghasilkan sebuah matriks baru dengan cara menukarkan posisi elemen baris dan kolom nya. Jadi, nanti hasil dari matriks tranpose nya adalah elemen baris menjadi elemen kolom dan elemen kolom menjadi elemen baris.

  f. Invers adalah metode dalam maatriks yang menghasilkan suatu matriks identitas yang memiliki nilai 1 pada diagonal utamanya dan memiliki nilai 0 pada koordinat lainnya apabila dikalikan dengan matriks asalnya.

  g. Determinan dapat didefinisikan sebagai nilai selisih dari perkalian elemen-elemen pada diagonal utama dengan elemen-elemen pada diagonal sekunder yang bilangannya bernilai riil. Determinan pada matriks dilambangkan atau disimbolkan dengan "det(A)" atau |A| dengan hasil ad-bc.


# 4. JENIS-JENIS MATRIKS

  *   Matriks Baris (Row Matrix), matriks yang hanya memiliki satu baris.
  *   Matriks Kolom (Column Matrix)m, matriks yang hanya memiliki satu kolom.

  *   Matriks Persegi, matriks yang banyak barisnya sama dengan banyak kolomnya.
  *   Matriks Datar, matriks yang banyak barisnya lebih sedikit daripada kolomnya.

  *   Matriks Tegak, matriks yang banyak kolomnya lebih sedikit daripada barisnya.
  *   Matriks Nol (Zero Matrix), matriks yang semua elemen penyusunnya adalah nol.

  *   Matriks Diagonal, matriks yang semua elemen diatas dan dibawah diagonal adalah nol.
  *   Matriks Skalar, matriks diagonal yang semua elemen pada diagonalnya bernilai sama.

  *   Matriks Identitas, matriks diagonal yang semua elemen pada diagonal utamanya adalah 1.
  *   Matriks Segitiga Atas, matriks persegi yang elemen-elemennya di bawah diagonal utamanya adalah nol.

  *   Matriks Segitiga Bawah, matriks persegi yang elemen-elemen di atas diagonal utamanya adalah nol.
  *   Matriks Simetri, matriks persegi yang setiap elemennya, selain elemen diagonal adalah simetri terhadap diagonal utama.

  *   Matriks Simetri Miring, matriks simetri yang elemen-elemennya, selain elemen diagonal, saling berlawanan.
  *   Matriks Tranpose, matriks yang diperoleh dari memindahkan elemen-elemen baris menjadi elemen pada kolom dan elemen kolom menjadi elemen pada baris.


# 5. TRANPOSE MATRIKS

  Tranpose matriks merupakan metode dalam matriks yang dapat menghasilkan sebuah matriks baru dengan cara menukarkan posisi elemen baris dan kolom nya. Jadi, nanti hasil dari matriks tranpose nya adalah elemen baris menjadi elemen kolom dan elemen kolom menjadi elemen baris.

  Tranpose matriks dilambangkan atau disimbolkan dengan ($A^T$) atau bisa juga ditulis seperti A_T.

  Contoh Tranpose matriks:

  $$
  A =
  \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9 \\
  \end{bmatrix}
  $$

  $$
  A_T =
  \begin{bmatrix}
  1 & 4 & 7 \\
  2 & 5 & 8 \\
  3 & 6 & 9 \\
  \end{bmatrix}
  $$

In [4]:
import numpy as np

A = np.array([[2,7],[1,8],[4,9]])
A_T = A.transpose()

print("matriks A sebelum di transpose=\n", A)
print("ukuran matriks A adalah", A.shape)
print("matriks A setelah di transpose=\n", A_T)
print("ukuran A_transpose adalah", A_T.shape)

matriks A sebelum di transpose=
 [[2 7]
 [1 8]
 [4 9]]
ukuran matriks A adalah (3, 2)
matriks A setelah di transpose=
 [[2 1 4]
 [7 8 9]]
ukuran A_transpose adalah (2, 3)


# 6. IMPLEMENTASI MATRIKS DENGAN NUMPY


In [1]:
import numpy as np
A = np.array([[4, 7, 9, 1],[2, 3, 8, 5],[6, 1, 9, 3]])
B = np.array([[3, 9, 5],[2, 7, 1],[8, 4, 6], [1, 5, 3]])
C = np.array([[4, 9, 1, 7],[5, 2, 8, 3]])
D = np.array([[3, 8],[5, 1],[9, 2]])

print("A=\n",A)
print("B=\n",B)
print("C=\n",C)
print("D=\n",D)

print("\n")

print("Ukuran matriks :",C.shape) # mencetak ukuran matriks
print("Jumlah baris :", C.shape[0])# mencetak jumlah baris
print("Jumlah kolom :", C.shape[1])# mencetak jumlah kolom

A=
 [[4 7 9 1]
 [2 3 8 5]
 [6 1 9 3]]
B=
 [[3 9 5]
 [2 7 1]
 [8 4 6]
 [1 5 3]]
C=
 [[4 9 1 7]
 [5 2 8 3]]
D=
 [[3 8]
 [5 1]
 [9 2]]


Ukuran matriks : (2, 4)
Jumlah baris : 2
Jumlah kolom : 4


# 7. OPERASI PADA MATRIKS

## A. PENJUMLAHAN MATRIKS

  Dua buah matriks dapat dijumlahkan apabila memiliki jumlah baris dan kolom (ordo) yang sama. `Contohnya adalah sebagai berikut:


In [5]:
import numpy as np

A = np.array([[4, 7, 9],[2, 3, 8],[6, 1, 9]])
B = np.array([[3, 9, 5],[2, 7, 1],[8, 4, 6]])

print("A=\n",A)
print("B=\n",B)
print("Hasil dari A+B adalah\n", A+B)

A=
 [[4 7 9]
 [2 3 8]
 [6 1 9]]
B=
 [[3 9 5]
 [2 7 1]
 [8 4 6]]
Hasil dari A+B adalah
 [[ 7 16 14]
 [ 4 10  9]
 [14  5 15]]


## B. PENGURANGAN MATRIKS

   Sama dengan syarat untuk dapat menjumlahkan matriks, dua buah matriks juga hanya dapat dikurangkan apabila memiliki jumlah baris dan kolom (ordo) yang sama. Contohnya adalah sebagai berikut:

In [6]:
import numpy as np

A = np.array([[4, 7, 9],[2, 3, 8],[6, 1, 9]])
B = np.array([[3, 9, 5],[2, 7, 1],[8, 4, 6]])

print("A=\n",A)
print("B=\n",B)
print("Hasil dari A-B adalah\n", A-B)

A=
 [[4 7 9]
 [2 3 8]
 [6 1 9]]
B=
 [[3 9 5]
 [2 7 1]
 [8 4 6]]
Hasil dari A-B adalah
 [[ 1 -2  4]
 [ 0 -4  7]
 [-2 -3  3]]


## C. PERKALIAN MATRIKS

  Dua buah matriks dapat dikalikan apabila jumlah kolom pada matriks A sama dengan jumlah bari pada matriks B. Contohnya adalah sebagai berikut:

In [7]:
import numpy as np

A = np.array([[4, 7, 9, 1],[2, 3, 8, 5],[6, 1, 9, 3]])
B = np.array([[3, 9, 5],[2, 7, 1],[8, 4, 6], [1, 5, 3]])

print("A=\n",A)
print("B=\n",B)
print("Hasil dari A@B adalah\n", A@B)

A=
 [[4 7 9 1]
 [2 3 8 5]
 [6 1 9 3]]
B=
 [[3 9 5]
 [2 7 1]
 [8 4 6]
 [1 5 3]]
Hasil dari A@B adalah
 [[ 99 126  84]
 [ 81  96  76]
 [ 95 112  94]]


# 8. MENGALIKAN DUA BUAH MATRIKS DENGAN ORDO 4X4 MENGGUNAKAN PERULANGAN PYTHON

In [8]:
import numpy as np

def mul_matrix(a, b):
  if len(a[0]) != len(b):
    print("error --- require", len(a[0]), "but found", len(b), "error matrix")
    return None

  result = []
  for i in range(len(a)):
    row = []
    for j in range(len(b[0])):
      total = 0
      for k in range(len(b)):
        total += a[i][k] * b[k][j]
      row.append(total)
    result.append(row)

  return result

matrixA = np.array([[2, 8], [6, 3], [1, 5]])
matrixB = np.array([[1, 5, 2], [2, 4, 3]])

result = mul_matrix(matrixA, matrixB)
if result:
    print("Matriks A:\n",matrixA)
    print("Matriks B:\n",matrixB)
    print("Hasil perkalian matriks A dan B :")
    for row in result:
        print(row)

Matriks A:
 [[2 8]
 [6 3]
 [1 5]]
Matriks B:
 [[1 5 2]
 [2 4 3]]
Hasil perkalian matriks A dan B :
[18, 42, 28]
[12, 42, 21]
[11, 25, 17]


# REFERENSI

1. https://www.kompas.com/skola/read/2023/05/22/213000069/pengertian-dan-jenis-jenis-matriks-pada-matematika?page=all

2. https://www.ruangguru.com/blog/mengenal-matriks-dalam-matematika-pengertian-jenis-dan-transpose

3. https://fti.ars.ac.id/blog/content/matriks--jenis-jenis-matriks

4. https://www.cuemath.com/algebra/transpose-of-a-matrix/

5. https://byjus.com/maths/inverse-matrix/

6. https://akupintar.id/info-pintar/-/blogs/matriks-pengertian-operasi-determinan-invers-dan-contoh-soal

